name: meftun

description: A featherweight messaging platform.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: 1.0.3
  cupertino_icons: ^1.0.2
  path: ^1.8.0
  flutter_slidable:
  file_picker: ^3.0.2+2
  fl_chart: ^0.36.2
  sembast: ^3.1.0+2
  sembast_web: ^2.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - logo.png
    - avatar.png
    - group_avatar.png
    - bot_avatar.png
